# Generated by Django 5.2.17 on 2026-08-31 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('extra_phone', models.CharField(blank=True, max_length=30)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('landmark', models.CharField(blank=True, max_length=160)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('delivery_method', models.CharField(choices=[('pickup', 'استلام من المطعم'), ('delivery', 'توصيل')], max_length=12)),
                ('payment_method', models.CharField(default='cash_on_delivery', editable=False, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('out', 'في الطريق'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('extras', models.JSONField(blank=True, default=list)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.product')),
            ],
        ),
    ]
