# Generated by Django 5.2.17 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('orders', '0001_initial')]

    operations = [
        migrations.AddField(model_name='order', name='delivery_address', field=models.TextField(blank=True)),
        migrations.AlterField(model_name='order', name='customer_name', field=models.CharField(blank=True, max_length=120)),
    ]
